export const RESTAURENT_SIGNIN_REQUEST = 'RESTAURENT_SIGNIN_REQUEST';
export const RESTAURENT_SIGNIN_SUCCESS = 'RESTAURENT_SIGNIN_SUCCESS';
export const RESTAURENT_SIGNIN_FAIL = 'RESTAURENT_SIGNIN_FAIL';


export const RESTAURENT_REGISTER_REQUEST = 'RESTAURENT_REGISTER_REQUEST';
export const RESTAURENT_REGISTER_SUCCESS = 'RESTAURENT_REGISTER_SUCCESS';
export const RESTAURENT_REGISTER_FAIL = 'RESTAURENT_REGISTER_FAIL';

export const RESTAURENT_LOGOUT = 'RESTAURENT_LOGOUT';